#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Sergio Souza'
        hostname: sf314vml
        username: shb
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Recife"
    codecs:
        install: true
    drivers:
        install: true
#    storage:
#        layout: gpt
#        swap:
#            size: 1G
#        volumes:
#          - mount: /
#          format: ext4
#          size: 100%
#          options:
#            - encrypt=luks2 # Criptografa a partição raiz com LUKS2
#            - luks_name=cryptroot # Define o nome da partição criptografada
#    packages:
#      - flatpak
#    pre_command: 
#      modprobe dm-crypt
#      modprobe dm-thin-provisioning
#      cryptsetup luksFormat /dev/sda --type luks2
#      cryptsetup luksOpen /dev/sda cryptroot
#      mkfs.ext4 /dev/mapper/cryptroot
#    late_command: 
#      flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
#      flatpak install flathub com.spotify.Client -y
#      flatpak install flathub com.brave.Browser -y
    updates: all
    shutdown: reboot

