#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Sergio Souza'
        hostname: sf314vml
        username: shb
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Recife"   
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
